
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLOR COMMA DRAW EQUALS EXIT FLOAT IDENTIFIER INT LPAREN POINTS PRINT RPAREN SET SHAPE\n    run : var_assign\n        | get_var\n        | print\n        | draw\n        | exit_program\n        | empty\n    \nvar_assign : SET IDENTIFIER EQUALS INT\n           | SET IDENTIFIER EQUALS FLOAT\n           | SET IDENTIFIER EQUALS SHAPE\n           | SET IDENTIFIER EQUALS COLOR\n           | SET IDENTIFIER EQUALS POINTS\n           | SET IDENTIFIER EQUALS get_var\n    \n    exit_program : EXIT LPAREN RPAREN\n    \n    get_var : IDENTIFIER\n    \n    print : PRINT LPAREN expression RPAREN\n    \n    draw : drawRec\n         | drawCircle\n    \n    drawCircle : DRAW SHAPE expression COMMA expression COMMA expression\n               | DRAW expression expression COMMA expression COMMA expression\n    \n    drawRec : DRAW SHAPE expression COMMA expression COMMA expression COMMA expression COMMA expression\n            | DRAW expression expression COMMA expression COMMA expression COMMA expression COMMA expression\n    \n    expression : get_var\n               | INT\n               | FLOAT\n               | POINTS\n               | COLOR\n    \n    empty :\n    '
    
_lr_action_items = {'SET':([0,],[8,]),'IDENTIFIER':([0,8,9,14,16,18,19,20,21,22,23,24,25,37,38,41,42,45,46,49,50,],[9,15,-14,9,9,9,9,-22,-23,-24,-25,-26,9,9,9,9,9,9,9,9,9,]),'PRINT':([0,],[10,]),'EXIT':([0,],[13,]),'$end':([0,1,2,3,4,5,6,7,9,11,12,20,21,22,23,24,27,30,31,32,33,34,35,36,43,44,51,52,],[-27,0,-1,-2,-3,-4,-5,-6,-14,-16,-17,-22,-23,-24,-25,-26,-13,-7,-8,-9,-10,-11,-12,-15,-18,-19,-20,-21,]),'DRAW':([0,],[14,]),'INT':([9,14,16,18,19,20,21,22,23,24,25,37,38,41,42,45,46,49,50,],[-14,21,21,21,21,-22,-23,-24,-25,-26,30,21,21,21,21,21,21,21,21,]),'FLOAT':([9,14,16,18,19,20,21,22,23,24,25,37,38,41,42,45,46,49,50,],[-14,22,22,22,22,-22,-23,-24,-25,-26,31,22,22,22,22,22,22,22,22,]),'POINTS':([9,14,16,18,19,20,21,22,23,24,25,37,38,41,42,45,46,49,50,],[-14,23,23,23,23,-22,-23,-24,-25,-26,34,23,23,23,23,23,23,23,23,]),'COLOR':([9,14,16,18,19,20,21,22,23,24,25,37,38,41,42,45,46,49,50,],[-14,24,24,24,24,-22,-23,-24,-25,-26,33,24,24,24,24,24,24,24,24,]),'RPAREN':([9,17,20,21,22,23,24,26,],[-14,27,-22,-23,-24,-25,-26,36,]),'COMMA':([9,20,21,22,23,24,28,29,39,40,43,44,47,48,],[-14,-22,-23,-24,-25,-26,37,38,41,42,45,46,49,50,]),'LPAREN':([10,13,],[16,17,]),'SHAPE':([14,25,],[18,32,]),'EQUALS':([15,],[25,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'run':([0,],[1,]),'var_assign':([0,],[2,]),'get_var':([0,14,16,18,19,25,37,38,41,42,45,46,49,50,],[3,20,20,20,20,35,20,20,20,20,20,20,20,20,]),'print':([0,],[4,]),'draw':([0,],[5,]),'exit_program':([0,],[6,]),'empty':([0,],[7,]),'drawRec':([0,],[11,]),'drawCircle':([0,],[12,]),'expression':([14,16,18,19,37,38,41,42,45,46,49,50,],[19,26,28,29,39,40,43,44,47,48,51,52,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> run","S'",1,None,None,None),
  ('run -> var_assign','run',1,'p_run','geo.py',99),
  ('run -> get_var','run',1,'p_run','geo.py',100),
  ('run -> print','run',1,'p_run','geo.py',101),
  ('run -> draw','run',1,'p_run','geo.py',102),
  ('run -> exit_program','run',1,'p_run','geo.py',103),
  ('run -> empty','run',1,'p_run','geo.py',104),
  ('var_assign -> SET IDENTIFIER EQUALS INT','var_assign',4,'p_var_assign','geo.py',113),
  ('var_assign -> SET IDENTIFIER EQUALS FLOAT','var_assign',4,'p_var_assign','geo.py',114),
  ('var_assign -> SET IDENTIFIER EQUALS SHAPE','var_assign',4,'p_var_assign','geo.py',115),
  ('var_assign -> SET IDENTIFIER EQUALS COLOR','var_assign',4,'p_var_assign','geo.py',116),
  ('var_assign -> SET IDENTIFIER EQUALS POINTS','var_assign',4,'p_var_assign','geo.py',117),
  ('var_assign -> SET IDENTIFIER EQUALS get_var','var_assign',4,'p_var_assign','geo.py',118),
  ('exit_program -> EXIT LPAREN RPAREN','exit_program',3,'p_exit_program','geo.py',125),
  ('get_var -> IDENTIFIER','get_var',1,'p_get_var','geo.py',132),
  ('print -> PRINT LPAREN expression RPAREN','print',4,'p_print','geo.py',139),
  ('draw -> drawRec','draw',1,'p_draw_shape','geo.py',146),
  ('draw -> drawCircle','draw',1,'p_draw_shape','geo.py',147),
  ('drawCircle -> DRAW SHAPE expression COMMA expression COMMA expression','drawCircle',7,'p_drawCircle','geo.py',154),
  ('drawCircle -> DRAW expression expression COMMA expression COMMA expression','drawCircle',7,'p_drawCircle','geo.py',155),
  ('drawRec -> DRAW SHAPE expression COMMA expression COMMA expression COMMA expression COMMA expression','drawRec',11,'p_drawRec','geo.py',162),
  ('drawRec -> DRAW expression expression COMMA expression COMMA expression COMMA expression COMMA expression','drawRec',11,'p_drawRec','geo.py',163),
  ('expression -> get_var','expression',1,'p_experession','geo.py',170),
  ('expression -> INT','expression',1,'p_experession','geo.py',171),
  ('expression -> FLOAT','expression',1,'p_experession','geo.py',172),
  ('expression -> POINTS','expression',1,'p_experession','geo.py',173),
  ('expression -> COLOR','expression',1,'p_experession','geo.py',174),
  ('empty -> <empty>','empty',0,'p_empty','geo.py',181),
]
